services:
  db:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: opto_simulator
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - db_data_opto_simulator:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db_data_opto_simulator: